# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "ok-to-test"
  # Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      ## group all dependencies with a k8s.io prefix into a single PR.
      kubernetes:
        patterns: [ "k8s.io/*" ]
      ## group all dependencies with a github.com/onsi prefix into a single PR.
      ginkgo:
        patterns: [ "github.com/onsi/*" ]
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "sigs.k8s.io/cluster-api/test"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "go.etcd.io/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "google.golang.org/grpc"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    commit-message:
      prefix: ":seedling:"
    labels:
      - "ok-to-test"

  # Test Go module
  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "monthly"
    ## group all dependencies with a k8s.io prefix into a single PR.
    groups:
      kubernetes:
        patterns: [ "k8s.io/*" ]
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "sigs.k8s.io/cluster-api/test"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "go.etcd.io/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "google.golang.org/grpc"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    commit-message:
      prefix: ":seedling:"
    labels:
      - "ok-to-test"
