before:
  hooks:
    - make release

builds:
- id: "clusterctl-operator"
  main: ./cmd/plugin
  binary: bin/clusterctl-operator
  env:
    - CGO_ENABLED=0
  ldflags:
  - -s -w 
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitMajor={{.Major}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitMinor={{.Minor}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitVersion={{.Version}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitCommit={{.Commit}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.gitTreeState={{.GitTreeState}}'
  - -X 'sigs.k8s.io/cluster-api-operator/version.buildDate={{.Date}}'
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
archives:
- id: clusterctl-operator
  builds:
  - clusterctl-operator
  name_template: "clusterctl-operator_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: false
